// <auto-generated />
using System;
using ContactReportApp.ReportApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ContactReportApp.ReportApi.Migrations
{
    [DbContext(typeof(ReportDBContext))]
    [Migration("20211223193239_reportdb")]
    partial class reportdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ContactReportApp.ReportApi.Entities.Rapor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("text");

                    b.Property<int>("RaporDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Raporlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DosyaYolu = "test yolu",
                            RaporDurumu = 1,
                            RaporTarihi = new DateTime(2021, 12, 23, 22, 32, 38, 884, DateTimeKind.Local).AddTicks(7795)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
