// <auto-generated />
using ContactReportApp.ContactApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ContactReportApp.ContactApi.Migrations
{
    [DbContext(typeof(ContactDBContext))]
    [Migration("20211221111910_contactdb")]
    partial class contactdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ContactReportApp.ContactApi.Models.IletisimBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("BilgiIcerigi")
                        .HasColumnType("text");

                    b.Property<int>("BilgiTipi")
                        .HasColumnType("integer");

                    b.Property<int>("KisiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KisiId");

                    b.ToTable("IletisimBilgileri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilgiIcerigi = "05346985877",
                            BilgiTipi = 1,
                            KisiId = 1
                        },
                        new
                        {
                            Id = 2,
                            BilgiIcerigi = "suphi.bayrak@yahoo.com",
                            BilgiTipi = 2,
                            KisiId = 1
                        },
                        new
                        {
                            Id = 3,
                            BilgiIcerigi = "Bursa",
                            BilgiTipi = 3,
                            KisiId = 1
                        },
                        new
                        {
                            Id = 4,
                            BilgiIcerigi = "05385988877",
                            BilgiTipi = 1,
                            KisiId = 2
                        },
                        new
                        {
                            Id = 5,
                            BilgiIcerigi = "Istanbul",
                            BilgiTipi = 3,
                            KisiId = 2
                        });
                });

            modelBuilder.Entity("ContactReportApp.ContactApi.Models.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Suphi",
                            Firma = "Bir Firma",
                            Soyad = "Bayrak"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ahmet",
                            Firma = "Ikinci Firma",
                            Soyad = "Uslu"
                        });
                });

            modelBuilder.Entity("ContactReportApp.ContactApi.Models.IletisimBilgisi", b =>
                {
                    b.HasOne("ContactReportApp.ContactApi.Models.Kisi", "Kisi")
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");
                });

            modelBuilder.Entity("ContactReportApp.ContactApi.Models.Kisi", b =>
                {
                    b.Navigation("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
